version: '3'

services:
  php_dev_nginx:
    image: nginx:1.16.0-alpine
    container_name: php_dev_nginx
    ports:
      - ${NGINX_PORT:-80}:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ${WEB_ROOT_PATH:-/var/www/html}:/var/www/html
      - ${LOG_ROOT_PATH:-/var/log}/nginx:/var/log/nginx
      - /dev/shm:/dev/shm
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - php_dev_fpm
    restart: always
    env_file:
      - .env
    networks:
      - php_dev_net

  php_dev_fpm:
    image: php_dev_fpm
    container_name: php_dev_fpm
    build:
      context: ./dockerfiles/
      dockerfile: php_dev_fpm
    volumes:
      - ${WEB_ROOT_PATH:-/var/www/html}:/var/www/html
      - ${LOG_ROOT_PATH:-/var/log}/php-fpm:/var/log/php-fpm
      - /dev/shm:/dev/shm
      - /usr/share/GeoIP:/usr/share/GeoIP
    env_file:
      - .env
    environment:
      TZ: "Asia/Seoul"
      SERVER_TYPE: ${SERVER_TYPE:-LOCAL}
    depends_on:
      - php_dev_mysql
      - php_dev_redis
      - php_dev_memcached
    restart: always
    networks:
      - php_dev_net

  php_dev_mysql:
    image: mysql:5.7.26
    container_name: php_dev_mysql
    ports:
      - ${WEB_SERVER_MYSQL_PORT:-3306}:3306
    volumes:
      - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_SERVER_MYSQL_ROOT_PASSWORD:-footer1@3$}
    restart: always
    env_file:
      - .env
    networks:
      - php_dev_net

  php_dev_redis:
    image: redis:alpine
    container_name: php_dev_redis
    command: redis-server --requirepass ${WEB_SERVER_REDIS_PASSWORD:-footer1@3$}
    ports:
      - ${WEB_SERVER_REDIS_PORT:-6379}:6379
    restart: always
    env_file:
      - .env
    networks:
      - php_dev_net

  php_dev_memcached:
    image: memcached:alpine
    container_name: php_dev_memcached
    ports:
      - ${WEB_SERVER_MEMCACHED_PORT:-11211}:11211
    restart: always
    env_file:
      - .env
    networks:
      - php_dev_net

  scribe_to_redis:
    image: scribe_to_redis
    container_name: scribe_to_redis
    build:
      context: ./dockerfiles/
      dockerfile: scribe_to_redis
    ports:
      - ${SCRIBE_PORT:-1463}:1463
    volumes:
      - ./config/scribe/scribed.conf:/etc/scribed/scribed.conf
      - ${LOG_ROOT_PATH:-/var/log}/scribed:/game/log/scribed
    command: [scribed, '/etc/scribed/scribed.conf'] #foreground run
    restart: always
    tty: true
    env_file:
      - .env
    networks:
      - php_dev_net

networks:
  php_dev_net: